spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://10.13.17.20:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 10.13.17.20
    port: 6379
server:
  context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level:
#    com.imooc.LoggerTest: debug

wechat:
  # 公众账号，授权 跟支付相关
  mpAppId: wxb28117c111991fd9
  mpAppSecret: 4d8c087e7d7c64731f4a4ef321b86f87

  # 开放平台，卖家扫码登录使用 跟支付完全没有关系
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9xxxxxx

  # 支付平台的账号 商户号
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  # 证书，发起支付不需要证书，退款需要证书
  keyPath: /var/weixin_cert/h5.p12
  # 接受微信异步通知
  notifyUrl: http://sell.natapp4.cc/sell/pay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

projectUrl:
  wechatMpAuthorize: http://sellgio.natapp1.cc
  wechatOpenAuthorize: http://sellgio.natapp1.cc
  sell: http://sellgio.natapp1.cc
logging:
  level:
    com.imooc.dataobject.mapper: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml

# 又拍云服务 见 https://console.upyun.com/services/file/
upyun:
  bucketName: XXX
  userName: xxx
  password: xxxx
  imageHost: http://xxx.com/